# Generated by Django 4.2 on 2024-12-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Coach', 'Coach'), ('Director', 'Director')], max_length=50)),
                ('age_group', models.CharField(choices=[('Under 10', 'Under 10'), ('Under 12', 'Under 12'), ('Under 14', 'Under 14'), ('Under 16', 'Under 16')], max_length=20)),
                ('topic', models.CharField(max_length=150)),
                ('content', models.TextField()),
            ],
        ),
    ]
